server:
  port: 8080

spring:
  application:
    name: smart-doc-backend

  # ???????
  datasource:
    url: jdbc:mysql://localhost:3306/smart_doc_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  # ??????
  jpa:
    hibernate:
      ddl-auto: update # ???? Java ?????????? SQL
    show-sql: true     # ?????? SQL?????

  # ??????? (???????? PDF ????)
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# ??????Python AI ?????
ai-engine:
  url: http://127.0.0.1:8000